export const posts = [
  {
    slug: "how-to-choose-bespoke-wedding-suit-bay-area",
    title: "How to Choose a Bespoke Wedding Suit in the Bay Area",
    excerpt: "Everything you need to know to find the right custom suit for your Bay Area wedding — from fabric selection to lead times.",
    author: "Julian Zaragoza",
    date: "March 15, 2025",
    readTime: "6 min read",
    category: "Wedding",
    featured: true,
  },
  {
    slug: "what-does-a-custom-suit-cost",
    title: "What Does a Custom Suit Cost? A Transparent Guide",
    excerpt: "A clear, no-nonsense breakdown of bespoke suit pricing — what drives cost, what you get at each level, and what to expect at Fino.",
    author: "David Brenno",
    date: "March 1, 2025",
    readTime: "5 min read",
    category: "Pricing",
    featured: false,
  },
  {
    slug: "bespoke-vs-made-to-measure",
    title: "Bespoke vs. Made-to-Measure: What's the Real Difference?",
    excerpt: "The terms are used interchangeably — but they describe fundamentally different garments. Here's what separates them.",
    author: "Julian Zaragoza",
    date: "February 15, 2025",
    readTime: "4 min read",
    category: "Education",
    featured: false,
  },
  {
    slug: "best-fabrics-for-california-wedding",
    title: "The Best Fabrics for a California Wedding",
    excerpt: "California climate demands a specific approach to suiting. These are the fabrics that look beautiful and perform on your wedding day.",
    author: "David Brenno",
    date: "February 1, 2025",
    readTime: "5 min read",
    category: "Fabrics",
    featured: false,
  },
  {
    slug: "how-to-dress-for-silicon-valley-gala",
    title: "How to Dress for a Silicon Valley Gala",
    excerpt: "The tech world has its own interpretation of black tie. Here's how to navigate gala dressing when you need to command the room.",
    author: "Julian Zaragoza",
    date: "January 15, 2025",
    readTime: "4 min read",
    category: "Style Guide",
    featured: false,
  },
  {
    slug: "loro-piana-vs-dormeuil",
    title: "Loro Piana vs. Dormeuil: Which Fabric Is Right for You?",
    excerpt: "Two of the world's most prestigious mills — compared side by side. We break down feel, performance, and when to choose each.",
    author: "David Brenno",
    date: "January 1, 2025",
    readTime: "6 min read",
    category: "Fabrics",
    featured: false,
  },
  {
    slug: "why-los-gatos-bespoke-suits",
    title: "Why Los Gatos Is the Bay Area's Best-Kept Secret for Bespoke Suits",
    excerpt: "While San Francisco gets the attention, Los Gatos has quietly become home to the Bay Area's finest bespoke tailoring experience.",
    author: "Julian Zaragoza",
    date: "December 15, 2024",
    readTime: "4 min read",
    category: "Local",
    featured: false,
  },
  {
    slug: "how-far-in-advance-wedding-suit",
    title: "How Far in Advance Should You Order Your Wedding Suit?",
    excerpt: "Timing is everything. Order too late and you're rushed. Order right and you have the full range of options — and peace of mind.",
    author: "David Brenno",
    date: "December 1, 2024",
    readTime: "3 min read",
    category: "Wedding",
    featured: false,
  },
];
